### ISSUE TITLE
乗法的関数の和の計算量

### ISSUE THREAD

**Issue by hidesato-fujii** [NyaanNyaan/library#103]
https://nyaannyaan.github.io/library/multiplicative-function/sum-of-multiplicative-function.hpp

> DFS の計算量は葉でないノードの個数に一致して $\mathrm{O}\left(\frac{N^{\frac{3}{4}}}{\log N}\right)$ らしい。(参考文献のリンク先に書いてあるが中国語なので読めていない…) 

との記述がありますが、参考文献には "[6] said, the number of t is O(n^(1-ε))." と記載があり、実際こちらが正しいと思います。

証明
$n$ の最大素因子を $\mathrm{mpf}(n)$ と表すことにして、葉でないノードは $\displaystyle L(N):=\left\\\{\frac{n}{\mathrm{mpf}(n)} \middle| n\leq N\right\\\}$ の元と対応します。
一方、 $\epsilon > 0$ を任意にとり、 $N^\epsilon$ 未満の最大の素数を $P$、 $N^{1-\epsilon}$ 以下の $(P-1)$-smooth numberの集合を $S(N)$ 、  $PS(N):=\\\{Px | x\in S(N)\\\}$ と定めます。 $PS(N)$ は $N$ 以下の正整数からなる集合なので $\displaystyle L(N)\supset \left\\\{\frac{n}{\mathrm{mpf}(n)} \middle| n\in PS(N) \right\\\}=S(N)$ ですが、 $|S(N)|=\Omega(N^{1-\epsilon})$ です。

**Comment by NyaanNyaan** [comment]
ありがとうございます！(忘れていてすみません) 修正します

**Comment by NyaanNyaan** [comment]
修正しました
