### ISSUE TITLE
[bug] About the factorial modulo p

### ISSUE THREAD

**Issue by hly1204** [NyaanNyaan/library#21]
## **Describe the bug**

Sorry for bothering you. Actually i'm not sure if it is a bug. I'm learning how to shift the sample points to compute the factorial modulo a prime but it seems that when $\lbrace f(0),f(1),\dots ,f(n)\rbrace \cap \lbrace f(m),f(m+1),\dots ,f(n+m)\rbrace \neq \emptyset$, the program will fail. Setting <https://github.com/NyaanNyaan/library/blob/684054f90fb91096883d1a614aba9c3bd84a2640/verify/verify-yuki/yuki-0502.test.cpp#L8> the number to `5` and query $2!$ will cause an assertion. It seems to happen when the modulo is very small.

**Comment by hly1204** [comment]
Let $g_d(x):=\prod _ {i=1}^d(x+i)$. Start with $g_1(x)=x+1,g_1(0)=1,g_1(1)=2$ and we can use one(or two) shift(s) to get $g_1(2),g_1(3),g_1(4),g_1(5)$ and $g_2(x)=g_1(x)g_1(x+1)$ so we can compute $g_2(0)=g_1(0)g_1(1),g_2(2)=g_1(2)g_1(3),g_2(4)=g_1(4)g_1(5)$ and then we compute $g_2(6),g_2(8),g_2(10),g_2(12)$ and we can get $g_4(0),g_4(4),g_4(8),g_4(12),g_4(16)$. Keep doing this may give the same result? This may save some DFTs? I'm not sure if that's right. I learned this from <https://loj.ac/s/1110094>.

**Comment by NyaanNyaan** [comment]
Sorry for the delay in getting back to you. This bug has been fixed. Thanks!
