### ISSUE TITLE
How do I generate single file script from it ?

### ISSUE THREAD

**Issue by ishandutta2007** [NyaanNyaan/library#50]
Since the focus is competitive coding we would need to generate a single file once coding is done.
I suppose it is possible with libraries like [this](https://www.npmjs.com/package/codingame-cpp-merge)
I havent tried using libraries for competetive coding earlier so I am not aware of what most competitive coders who are using libraries are doing.
I would like to know what process the author is following.

**Comment by NyaanNyaan** [comment]
I use a tool called online-judge-tools to combine files into one.
[onilne-judge-tools](https://github.com/online-judge-tools)
