### ISSUE TITLE
[bug] 平方分割のテンプレートにバグがあります

### ISSUE THREAD

**Issue by 981377660LMT** [NyaanNyaan/library#62]
## **Describe the bug**
https://judge.yosupo.jp/submission/18026
https://judge.yosupo.jp/submission/127213
提出のコードを使わせていただきました。WAが出ました。

**Comment by NyaanNyaan** [comment]
報告ありがとうございます！

昨日から今日にかけて、Library Checker のジャッジが壊れていたようです。
https://twitter.com/yosupot/status/1628203763818430465

コードを再度提出したところ AC が出ました。よって、ライブラリではなく Library Checker に問題があったと考えています。
https://judge.yosupo.jp/submission/127254

**Comment by 981377660LMT** [comment]
> 報告ありがとうございます！
> 
> 昨日から今日にかけて、Library Checker のジャッジが壊れていたようです。 https://twitter.com/yosupot/status/1628203763818430465
> 
> コードを再度提出したところ AC が出ました。よって、ライブラリではなく Library Checker に問題があったと考えています。 https://judge.yosupo.jp/submission/127254

ありがとうございます。別の場所でチェックし確認した結果、確かにライブラリに問題はありません。
