### ISSUE TITLE
[bug] 多項式/形式的冪級数ライブラリの log の定義について

### ISSUE THREAD

**Issue by ebi-fly13** [NyaanNyaan/library#74]
## **Describe the bug**
[多項式/形式的冪級数ライブラリ](https://nyaannyaan.github.io/library/fps/formal-power-series.hpp) の log の定義についてですが、 「 $e^f \equiv g \mod x^n$ を満たす $g$ 」ではなく、「 $f \equiv e^g \mod x^n$ を満たす $g$ 」 だと思います。

**Comment by NyaanNyaan** [comment]
ありがとうございます、修正しました (慣れてない時期の文章だったので、これを機に色々と書き換えました)
