### ISSUE TITLE
二次元セグ木のidがconstになってません[bug] 

### ISSUE THREAD

**Issue by aplysia56108** [NyaanNyaan/library#95]
## **Describe the bug**
二次元セグ木のgetメソッドはconstになっている一方、その中で呼び出しているidメソッドはconstになっていません。getを使用するとコンパイル時にerrorになってしまいます。

**Comment by NyaanNyaan** [comment]
ありがとうございます！修正します

**Comment by aplysia56108** [comment]
ありがとうございます！！
