### ISSUE TITLE
[bug] SternBrocotTree について

### ISSUE THREAD

**Issue by potato167** [NyaanNyaan/library#97]
## **Describe the bug**
https://github.com/NyaanNyaan/library/blob/master/math/stern-brocot-tree.hpp

26 行目、30 行目が int になっているが、Int であるべきだと思います。 

## **Additional context**

例えば、Int = long long として、 X=1,Y=1e18 を入れるとオーバーフローが発生します。

**Comment by NyaanNyaan** [comment]
報告ありがとうございます！修正します

**Comment by NyaanNyaan** [comment]
修正しました
